POST http://localhost:8080/events

Content-Type: application/json
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI5Njg1NjU1LCJ1c2VySWQiOjEsInVzZXJOYW1lIjoidGVzdCJ9.C8c3JUqcz70sRQd4cEx08c48nknTATgKGAOeoG_gnok

{
  "name": "Tech Conference 2024",
  "description": "Annual technology conference featuring the latest innovations in AI and machine learning.",
  "dateTime": "2024-09-15T09:00:00Z",
  "location": "Silicon Valley Convention Center",
}